# Generated by Django 4.2.16 on 2024-11-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockscrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='unique_sym',
            new_name='symbol',
        ),
    ]
