# Generated by Django 5.1 on 2024-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role_num',
            new_name='roll_num',
        ),
    ]
