# Generated by Django 5.1 on 2024-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_employment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='employment_id',
            new_name='employee_id',
        ),
    ]
