# Generated by Django 5.1 on 2024-08-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_rename_employment_id_employment_employee_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employment',
            new_name='Employee',
        ),
    ]
